# Generated by Django 5.2.6 on 2025-09-22 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transaction_code", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=20)),
                ("paid_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("held_by_platform", models.BooleanField(default=True)),
                (
                    "artisan",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "artisan"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artisan_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
