# Generated by Django 5.2.6 on 2025-09-22 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="inventory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.inventory",
            ),
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="item",
            field=models.ManyToManyField(related_name="item", to="cart.item"),
        ),
    ]
