# Generated by Django 5.2.6 on 2025-09-22 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0003_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customdesignrequest",
            name="artisan",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "artisan"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_requests_as_artisan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customdesignrequest",
            name="buyer",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "buyer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_requests_as_buyer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="artisan",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "artisan"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "buyer"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cart.shoppingcart",
            ),
        ),
        migrations.AddField(
            model_name="orderstatus",
            name="artisan",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "artisan"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderstatus",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="buyer",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "buyer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
    ]
